PRN211_Project/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;
using PRN211_Project.Models;
using System.Collections.Specialized;
using System.Text.Json;

namespace PRN211_Project.Controllers
{
    public class GenresController : Controller
    {
        public IActionResult GenreManagement()
        {
            Person user = new Person();
            if (HttpContext.Session.GetString("account") != null)
            {
                user = (Person)JsonSerializer.Deserialize<Person>(HttpContext.Session.GetString("account"));
            }

            if (user.Type == 1)
            {
                using (var context = new CenimaDBContext())
                {
                    List<Genre> listG = context.Genres.ToList();
                    ViewBag.listG = listG;
                    if (TempData["shortMessage"] != null)
                    {
                        ViewBag.Message = TempData["shortMessage"].ToString();
                    }

                    return View(listG);
                }
            }
            ViewData["message"] = "Error 404 Not found!";
            return View("../Shared/Error");

        }

        public IActionResult Edit(int id)
        {
            using (var context = new CenimaDBContext())
            {
                Genre genre = context.Genres.SingleOrDefault(c => c.GenreId == id);
                return PartialView("editGenre", genre);
            }
        }

        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            using (var context = new CenimaDBContext())
            {
                context.Update(genre);
                context.SaveChanges();
                return RedirectToAction("GenreManagement");
            }
        }

        public IActionResult Delete(int id)
        {
            using (var context = new CenimaDBContext())
            {
                Genre genre = context.Genres.SingleOrDefault(c => c.GenreId == id);
                return PartialView("deleteGenre", genre);
            }
        }

        [HttpPost]
        public IActionResult Delete(Genre genre)
        {
            using (var context = new CenimaDBContext())
            {
                Movie movie = context.Movies.FirstOrDefault(c => c.GenreId == genre.GenreId);
                if (movie == null)
                {
                    context.Remove(genre);
                    context.SaveChanges();
                    return RedirectToAction("GenreManagement");
                }
                else
                {
                    TempData["shortMessage"] = "This Genre is currently in use";
                    return RedirectToAction("GenreManagement");
                }

            }
        }

        [HttpPost]
        public IActionResult Add()
        {
            using (var context = new CenimaDBContext())
            {
                string desc = this.Request.Form["des"];
                Genre genre = new Genre()
                {
                    Description = desc
                };
                context.Genres.Add(genre);
                context.SaveChanges();
                return RedirectToAction("GenreManagement");
            }
        }
    }
}

PRN211_Project/Controllers/LoginController.cs
using GoogleAuthentication.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN211_Project.Models;
using System;
using System.Security.Principal;
using System.Text.Json;
using static System.Net.Mime.MediaTypeNames;

namespace PRN211_Project.Controllers
{
	public class LoginController : Controller
	{
		public IActionResult Signin()
		{
			var ClientID = "625640582952-khuslr7j429aa0kb13eg93rql0nj95vc.apps.googleusercontent.com";
			var url = "http://localhost:5228/Login/LoginGoogle";
			var response = GoogleAuth.GetAuthUrl(ClientID, url);
			ViewBag.response = response;
			return View();
		}

		[HttpPost]
		public IActionResult Signin(Person person)
		{
			if (ModelState.IsValid)
			{
				if (string.IsNullOrEmpty(HttpContext.Session.GetString("account")))
				{
					using (var context = new CenimaDBContext())
					{
						var account = context.Persons.Where(a => a.Email == person.Email && a.Password == person.Password).SingleOrDefault();
						if (account != null)
						{
							HttpContext.Session.SetString("account", System.Text.Json.JsonSerializer.Serialize(account));
							return RedirectToAction("Index", "Home");
						}
						else
						{
							TempData["Message"] = "Đăng Nhập Không Thành Công";
							return View();
						}
					}
				}
				else
				{
					TempData["Message"] = "Đã Đăng Nhập Tài Khoản Rồi !!!";
					return RedirectToAction("Index", "Home");
				}
			}
			return View();
		}

		public async Task<IActionResult> LoginGoogle(string code)
		{
			if (string.IsNullOrEmpty(HttpContext.Session.GetString("account")))
			{
				var ClientID = "625640582952-khuslr7j429aa0kb13eg93rql0nj95vc.apps.googleusercontent.com";
				var ClientSecret = "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";
				var url = "http://localhost:5228/Login/LoginGoogle";
				var token = await GoogleAuth.GetAuthAccessToken(code, ClientID, ClientSecret, url);
				var userProfile = await GoogleAuth.GetProfileResponseAsync(token.AccessToken.ToString());
				var googleUser = JsonConvert.DeserializeObject<userGoogle>(userProfile);
				if (googleUser.Verified_Email == true)
				{
					using (var context = new CenimaDBContext())
					{
						var checkEmail = context.Persons.Where(c => c.Email == googleUser.Email).SingleOrDefault();
						Person person = new Person();
						if (checkEmail == null)
						{
							person.Fullname = googleUser.Name;
							person.Email = googleUser.Email;
							person.Gender = "";
							person.Password = "";
							person.Type = 2;
							person.IsActive = true;
							context.Add(person);
							context.SaveChanges();
							var account = context.Persons.Where(c => c.Email == googleUser.Email).SingleOrDefault();
							HttpContext.Session.SetString("account", System.Text.Json.JsonSerializer.Serialize(account));
							return RedirectToAction("Index", "Home");
						}
						else if (string.IsNullOrEmpty(checkEmail.Password))
						{
							HttpContext.Session.SetString("account", System.Text.Json.JsonSerializer.Serialize(checkEmail));
							return RedirectToAction("Index", "Home");
						}
						else
						{
							TempData["Message"] = "Email Đã Tồn Tại !!!";
							return RedirectToAction("Signin");
						}
					}
				}
				else
				{
					TempData["Message"] = "Đăng Nhập Không Thành Công";
					return RedirectToAction("Signin");
				}
			}
			else
			{
				TempData["Message"] = "Đã Đăng Nhập Tài Khoản Rồi !!!";
				return RedirectToAction("Index", "Home");
			}
		}

		public IActionResult Signout()
		{
			if ((HttpContext.Session.GetString("account") != null) || string.IsNullOrEmpty(HttpContext.Session.GetString("account")))
			{
				HttpContext.Session.Remove("account");
			}
			return RedirectToAction("Index", "Home");
		}

		public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Register(Person person)
		{
			if (ModelState.IsValid)
			{
				using (var context = new CenimaDBContext())
				{
					if (context.Persons.Where(p => p.Email == person.Email).SingleOrDefault() != null)
					{
						ViewBag.exist = "Email Đã Tồn Tại !!!";
						return View();
					}
					else
					{
						var account = context.Persons.Add(new Person
						{
							Fullname = person.Fullname,
							Gender = person.Gender,
							Email = person.Email,
							Password = person.Password,
							Type = 2,
							IsActive = true,
						});
						if (account != null)
						{
							TempData["Message"] = "Đăng Ký Thành Công";
							context.SaveChanges();
							return RedirectToAction("Signin");
						}
					}
				}
			}
			return View();
		}

		public IActionResult Reset()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Reset(Person person)
		{
			Random rd = new Random();
			using (var context = new CenimaDBContext())
			{
				var account = context.Persons.Where(a => a.Email == person.Email).SingleOrDefault();
				if (account != null)
				{
					IEmailService emailService = new EmailService();
					string otp = rd.Next(0, 1000000).ToString("D6");
					HttpContext.Session.SetString("otp", otp);
					emailService.SendEmail(person.Email, "OTP Change Password", otp);
					HttpContext.Session.SetString("pid", account.PersonId.ToString());
					return RedirectToAction("Otp");
				}
				else
				{
					ViewBag.text = "Email Không Tồn Tại!!!";
					return View();
				}
			}
		}

		public IActionResult Otp()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Otp(Person person)
		{
			string otpValue = HttpContext.Request.Form["otpValue"].ToString().Trim();
			var otpSession = HttpContext.Session.GetString("otp");
			if (otpSession != null)
			{
				if (otpSession.Trim().Equals(otpValue))
				{
					return RedirectToAction("Repassword");
				}
				else
				{
					ViewBag.error = "OTP Không Chính Xác !!!";
					return View();
				}
			}
			return View();
		}

		public IActionResult Repassword()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Repassword(Person person)
		{
			var id = HttpContext.Session.GetString("pid");
			string pass = HttpContext.Request.Form["pass"];
			string repass = HttpContext.Request.Form["repass"];
			if (pass.Equals(repass))
			{
				using (var context = new CenimaDBContext())
				{
					var account = context.Persons.Where(a => a.PersonId == Convert.ToInt32(id)).SingleOrDefault();
					if (account != null)
					{
						account.Password = pass;
						TempData["Message"] = "Đổi Mật Khẩu Thành Công";
						context.SaveChanges();
						HttpContext.Session.Remove("pid");
						return RedirectToAction("Signin");
					}
				}
			}
			else
			{
				ViewBag.error = "Mật Khẩu Mới Không Khớp !!!";
				return View();
			}
			return View();
		}
	}
}

PRN211_Project/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using PRN211_Project.Models;
using System.Collections.Generic;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using static System.Net.WebRequestMethods;
using System.Text.Json;

namespace PRN211_Project.Controllers
{
	public class MovieController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public IWebHostEnvironment HostEnvironment { get; }

		//private readonly CenimaDBContext _db;




		public MovieController(ILogger<HomeController> logger, IWebHostEnvironment hostEnvironment)
		{
			_logger = logger;
			HostEnvironment = hostEnvironment;



		}
		public IActionResult Index()
		{
			using (var context = new CenimaDBContext())
			{
				List<Movie> movies = context.Movies.ToList();
				Person user = new Person();
				if (HttpContext.Session.GetString("account") != null)
				{
					user = (Person)JsonSerializer.Deserialize<Person>(HttpContext.Session.GetString("account"));
					if (user.Type != 1)
					{
						return RedirectToAction("Signin", "Login");
					}
				}
				else
				{
					return RedirectToAction("Signin", "Login");

				}
				return View(movies);
			}

		}
		public IActionResult Create()
		{
			using (var context = new CenimaDBContext())
			{
				ViewData["Genre"] = new SelectList(context.Genres, "GenreId", "Desciption");
				List<Genre> g = context.Genres.ToList();
				ViewBag.Genres = g;
				return View();
			}

		}

		//public IActionResult Create()
		//{
		//   ViewData["CategoryId"] = new SelectList(_dbConText.Categories, "CategoryId", "CategoryName");
		//   return View();
		//}

		[HttpPost]
		[ValidateAntiForgeryToken]

		public async Task<IActionResult> Create(Movie product)
		{
			using (var context = new CenimaDBContext())
			{
				// Kiem tra du lieu tren form da hop le chua

				if (ModelState.IsValid)
				{


					var fileName = Path.GetFileName(product.imageFile.FileName);
					var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\image", fileName);
					using (var fileStream = new FileStream(filePath, FileMode.Create))
					{
						await product.imageFile.CopyToAsync(fileStream);
					}


					//string wwwRootPath = HostEnvironment.WebRootPath;
					//string fileName = Path.GetFileNameWithoutExtension(product.imageFile.FileName);
					//string extension = Path.GetExtension(product.imageFile.FileName);

					//product.Image = fileName = fileName + DateTime.Now.ToString() + extension;
					//string path = Path.Combine(wwwRootPath + "/image/", fileName);
					//using (var fileStream = new FileStream(path, FileMode.Create))
					//{
					//   await product.imageFile.CopyToAsync(fileStream);
					//}
					product.Image = product.imageFile.FileName;
					context.Add(product);
					context.SaveChanges();
					return RedirectToAction("Index");
				}
				ViewData["GenreId"] = new SelectList(context.Genres, "GenreId", "Description");
				product.Image = Path.GetFileName(product.imageFile.FileName);
				List<Genre> g = context.Genres.ToList();

				ViewBag.Genres = g;

				return View(product);
			}
		}



		[HttpGet]
		public IActionResult Edit(int id)

		{
			using (var context = new CenimaDBContext())
			{
				List<Genre> list = context.Genres.ToList();
				var movie = context.Movies.Where(p => p.MovieId == id).SingleOrDefault();
				if (movie == null)
				{
					TempData["MessageUpdate"] = "phim khong ton tai";
					return RedirectToAction("Index");

				}
				else
				{
					ViewData["GenreId"] = new SelectList(list, "GenreId", "Description");
					ViewBag.image = "~/image/" + movie.Image;
					return View(movie);
				}
			}
		}
		[HttpPost]
		public async Task<IActionResult> Edit(Movie product)
		{


			using (var context = new CenimaDBContext())
			{
				Movie p = context.Movies.SingleOrDefault(p => p.MovieId == product.MovieId);
				if (p != null)
				{
					var fileName = Path.GetFileName(product.imageFile.FileName);
					var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\image", fileName);
					using (var fileStream = new FileStream(filePath, FileMode.Create))
					{
						await product.imageFile.CopyToAsync(fileStream);
					}


					p.Image = product.imageFile.FileName;
					p.Title = product.Title;

					p.Description = product.Description;

					p.GenreId = product.GenreId;
					context.SaveChanges();
					TempData["MessageUpdate"] = "Update Successful";
					return RedirectToAction("Index");
				}

				ViewData["GenreId"] = new SelectList(context.Genres.ToList(), "GenreId", "Description");


				return View(p);
			}

			//public IActionResult Edit(int id)

			//{
			//   //using (var context = new CenimaDBContext())
			//   //{
			//      if (_db.Movies.SingleOrDefault(p => p.MovieId == id) == null)
			//      {
			//         ViewData["message"] = "this movie is not exist";
			//         return View("../error");

			//      }
			//      else
			//      {
			//         var p = _db.Movies.FirstOrDefault(p => p.MovieId == id);
			//         ViewData["GenreId"] = new SelectList(_db.Genres, "GenreId", "Description");
			//         //List<Genre> g = context.Genres.ToList();
			//         //ViewBag.Genres = g;
			//         return View(p);
			//      }


			//}
			//[HttpPost]
			//public IActionResult Edit(Movie product)
			//{


			//   //if (ModelState.IsValid)
			//   //{
			//   Movie p = _db.Movies.SingleOrDefault(p => p.MovieId == product.MovieId);
			//   if (p != null)
			//   {
			//      p.Title = product.Title;

			//      p.Description = product.Description;

			//      p.GenreId = product.GenreId;
			//      _db.SaveChanges();
			//      ViewData["GenreId"] = new SelectList(_db.Genres, "GenreId", "Desciption");
			//      return RedirectToAction("Index");
			//   }
			//   return View(p);





			//   //}
			//   //return View(product);
			//}

			//public IActionResult Edit(int id)

			//{
			//   //using (var context = new CenimaDBContext())
			//   //{
			//      if (_db.Movies.SingleOrDefault(p => p.MovieId == id) == null)
			//      {
			//         ViewData["message"] = "this movie is not exist";
			//         return View("../error");

			//      }
			//      else
			//      {
			//         var p = _db.Movies.FirstOrDefault(p => p.MovieId == id);
			//         ViewData["GenreId"] = new SelectList(_db.Genres, "GenreId", "Description");
			//         //List<Genre> g = context.Genres.ToList();
			//         //ViewBag.Genres = g;
			//         return View(p);
			//      }






			//}
			//return View(product);
		}
		public IActionResult Delete(int id)
		{
			using (var context = new CenimaDBContext())
			{

				var rate = context.Rates.FirstOrDefault(p => p.MovieId == id);
				if (rate == null)
				{
					var m = context.Movies.Find(id);
					if (m != null)
					{
						context.Movies.Remove(m);
						context.SaveChanges();
						TempData["MessageUpdate"] = "Delete Successful";
						//return RedirectToAction("index");
					}
				}
				else
				{
					TempData["Message"] = "phim co danh gia";

					//return RedirectToAction("index");


				}
				return RedirectToAction("index");



			}



		}


	}
}

PRN211_Project/Views/Shared/_Layout.cshtml
@using System.Text.Json
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRN211_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRN211_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Phim Hay</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="justify-content: space-between;">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                        </li>
                        <form class="d-flex align-items-center" action="/Home/Search" method="get" style="color:red">
                            <input style="margin-left:600px;padding:5px 10px" type="text" name="search" placeholder="Nhập tên phim cần tìm" />
                            <input style="margin-left:20px" class="btn btn-outline-primary" type="submit" value="Tìm" />
                        </form>


                        @if (Context.Session.GetString("account") != null)
                        {

                            Person user = (Person)JsonSerializer.Deserialize<Person>(Context.Session.GetString("account"));
                            if (user.Type == 1)

                            {
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dropdown button
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="nav-link text-dark" asp-action="Index" asp-controller="Movie">Movie Management </a></li>
                                        <li><a class="nav-link text-dark" asp-action="GenreManagement" asp-controller="Genres">Genre Management </a></li>
                                        <li><a class="nav-link text-dark" asp-action="List" asp-controller="Members">User Management </a></li>
                                    </ul>
                                </div>
                               
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark">Welcome: @user.Fullname</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="signout">SignOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item" style="margin-left:100px">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="SignIn">Đăng nhập</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="register">Đăng ký</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PRN211_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>